name: TCP
favicon: null
layout_spectrum: 0
typography_spectrum: 0.64372
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f3b83b'
    - '#000000'
    - '#d62530'
    - '#ffffff'
    - '#c56f63'
  brandStrength: 0.13268143474124372
  lightness: 0.4369407924823463
  saturation: 0.1580054177902639
  rhythmicContrast: 0.34282065997831523
purpose: []
