name: TCP
favicon: null
layout_spectrum: 0.6357613035943359
typography_spectrum: 0.2278831689618528
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.13268143474124372
  lightness: 0.4369407924823463
  saturation: 0.1580054177902639
  rhythmicContrast: 0.34282065997831523
purpose: []
